services:
  postgres:
    image: postgres:16.1-alpine
    restart: always
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "peerloop_local"
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/postgres_data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 15433:80
    environment:
      PGADMIN_DEFAULT_EMAIL: "test@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "test"
    depends_on:
      - postgres
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/pgadmin_data:/var/lib/pgadmin

volumes:
  postgres_data:
  pgadmin_data:
